---

- hosts: all
  become: true
  tasks:

  - name: Ubuntu/Debian -- update apt repository index
    ansible.builtin.apt:
      update_cache: yes
    when: ansible_distribution in ["Debian", "Ubuntu"]

  - name: RedHat -- update yum repository index
    ansible.builtin.yum:
      update_cache: yes
    when: ansible_distribution == "RedHat" and ansible_distribution_major_version in ["6","7"]

  - name: RedHat -- update dnf repository index
    ansible.builtin.dnf:
      update_cache: yes
    when: ansible_distribution == "RedHat" and ansible_distribution_major_version in ["8","9"]
    
  - name: Fedora -- update dnf repository index
    ansible.builtin.dnf:
      update_cache: yes
    when: ansible_distribution == "Fedora"
   
  - name: Ubuntu/Debian -- apt install httpd package
    ansible.builtin.apt:
      name: apache2
      state: latest
    when: ansible_distribution in ["Debian", "Ubuntu"]

  - name: RedHat --  yum install httpd package
    ansible.builtin.yum:
      name: httpd
      state: latest
    when: ansible_distribution == "RedHat" and ansible_distribution_major_version in ["6","7"]

  - name: RedHat --  dnf install httpd package
    ansible.builtin.dnf:
      name: httpd
      state: latest
    when: ansible_distribution == "RedHat" and ansible_distribution_major_version in ["8","9"]

  - name: Fedora -- dnf install httpd package
    ansible.builtin.dnf:
      name: httpd
      state: latest
    when: ansible_distribution == "Fedora"

  - name: Ubuntu/Debian -- apt add php support for apache
    ansible.builtin.apt:
      name: libapache2-mod-php
      state: latest
    when: ansible_distribution in ["Debian", "Ubuntu"]

  - name: RedHat -- yum add php support for apache
    ansible.builtin.yum:
      name: php
      state: latest
    when: ansible_distribution == "RedHat" and ansible_distribution_major_version in ["6","7"]

  - name: RedHat -- dnf add php support for apache
    ansible.builtin.dnf:
      name: php
      state: latest
    when: ansible_distribution == "RedHat" and ansible_distribution_major_version in ["8","9"]

  - name: Fedora -- dnf add php support for apache
    ansible.builtin.dnf:
      name: php
      state: latest
    when: ansible_distribution == "Fedora"
